apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: app_db
        - name: MYSQL_ROOT_PASSWORD
          value: pass
      resources:
        requests:
          memory: 512Mi
          cpu: 150m
        limits:
          memory: 1.5Gi
          cpu: 500m
      volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql/
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: mysql-volume-claim
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS notes (
      ID int NOT NULL AUTO_INCREMENT, 
      text TEXT DEFAULT NULL, 
      PRIMARY KEY (ID)
    );

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql

---

apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: app-init
      image: busybox
      command: ['sh', '-c', 'until nc -z mysql-service 3306; do sleep 1; done;']
  containers:
    - name: app   
      image: app
      ports:
        - containerPort: 777
      env:
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: pass
        - name: DB_HOST
          value: mysql-service
        - name: DB_NAME
          value: app_db
      resources:
        requests:
          memory: 128Mi
          cpu: 150m
        limits:
          memory: 256Mi
          cpu: 500m
      imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  selector:
    app: app
  type: NodePort
